RT-8: Оформить репозиторий
frontend-park-mail-ru/2021_1_RedTech pull request #1
Opened 2021-02-14 19:46 UTC by timoninas

2021-02-15 09:58 UTC, Betchika99 requested changes
В целом очень хорошо. Нужно оставить еще место для API и добавить ссылку на гошную репу

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +# Redioteka
давай вот это уберем, потому что название есть на картинке, а потом в описании

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +Redioteka — это стриминговый сервис, позволяющий смотреть интересующие фильмы и сериалы зарегестрированным пользователям. У всех пользователей есть возможность оформить подписку на интересующий их ко
зарегистрированным - опечатка

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +Вы можете смотреть сколько угодно фильмов и сериалов без рекламы по фиксированной цене!
смотри, сейчас в описании идет смешение лиц, к которым оно обращается. Сначала ты пишешь как бы в общем "у всех пользователей", а зачем "Вы можете", т.е. обращаешься прямо ко мне, как к пользаку. Давай определимся со стилем. Мне больше нравится "продающее" описание вида "Здесь вы можете с легкостью оформить подписку на контент, который подходит именно вам, чтобы не пропустить новые видео!" и тому подобное

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +Вы можете смотреть сколько угодно фильмов и сериалов без рекламы по фиксированной цене!
также в описании нужно особенно выделить вашу фичу и чем вы отличаетесь от других сервисов

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +Redioteka — это стриминговый сервис, позволяющий смотреть интересующие фильмы и сериалы зарегестрированным пользователям. У всех пользователей есть возможность оформить подписку на интересующий их ко
что означает "подбирать"? это рекомендательная система будет на нейроночках?)) за каждое написанное слово придется делать фичу, лучше писать аккуратнее

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +<ol>
давай список уберем и напишем "В разработке" или "To be continued.."

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +(Добавить позже)
тоже самое "В разработке" или "To be continued.."

2021-02-15 09:58 UTC, Betchika99 commented on README.md
> +[redioteka.com](https://www.netflix.com/ru/)
ссылка забавная конечно))0)

2021-02-16 11:06 UTC, timoninas commented on README.md
> +Redioteka — это стриминговый сервис, позволяющий смотреть интересующие фильмы и сериалы зарегестрированным пользователям. У всех пользователей есть возможность оформить подписку на интересующий их ко
В том смысле, что пользователь может зайти в любой жанр и среди представленных фильмов выбрать какой он захочет. Наверное, в этом смысле употреблено слово "подбирать"

2021-02-16 11:53 UTC, timoninas commented on README.md
> +[redioteka.com](https://www.netflix.com/ru/)
Вставил ссылку, чтобы хоть как-то заполнить пустоту 🙃

2021-02-16 19:12 UTC, Betchika99 approved these changes

2021-02-16 19:12 UTC, merged