RT-76: Добавить dropdown меню для профиля
frontend-park-mail-ru/2021_1_RedTech pull request #23
Opened 2021-03-20 21:50 UTC by timoninas

2021-03-21 22:50 UTC, Betchika99 requested changes
- [ ] Добавить плюшки scss в код (вложенность например)
- [ ] Поработать над оптимизацией кода (например, убрать постоянное создание инстансов вьюх внутри обработчиков)
- [ ] Бага. После регистрации менюшка появляется только после обновления страницы. До этого показывается иконка входа
- [ ] CSS-совет. Добавить transition на выпадашку, чтобы она появлялась/исчезала более плавно
- [ ] Баг. На профиле пропадает шапка сайта, невозможно вернуться/перейти на другую страницу
- [ ] Переход на "Избранное" не работает в выпадашке. Лучше убрать/задизеблить этот пункт

2021-03-21 22:50 UTC, Betchika99 commented on src/components/DetailForm/DetailForm.scss
>    //display: table;
комменты удаляем

2021-03-21 22:50 UTC, Betchika99 commented on src/components/Header/Header.scss
> +    background-color: #0A0C0E;
почему не константа?

2021-03-21 22:50 UTC, Betchika99 commented on src/components/Header/Header.scss
> +      background-color: #0e1212;
почему не константа?

2021-03-21 22:50 UTC, Betchika99 commented on src/components/Header/Header.scss
> +    .item__dropdown-profile:hover {
у тебя же scss, почему не сделать вложенность и &:hover?

2021-03-21 22:50 UTC, Betchika99 commented on src/index.html
> +    <div id="app"></div>
что за изменение такое? го стрелку за гаражи, пояснишь за него)

2021-03-21 22:50 UTC, Betchika99 commented on src/main.js
> +    let data = {};
у вас тут походу с Никитой будут мерж конфликты, потому что у него headerIcons :(

2021-03-21 22:50 UTC, Betchika99 commented on src/views/DetailView/DetailView.js
> +            const profileView = new ProfileView();
каждый раз при клике создавать новый инстанс? звучит не очень производительно

2021-03-21 22:50 UTC, Betchika99 commented on src/views/HomeView/HomeView.js
> +            localStorage.removeItem('ID');
а мы разве не убираем локалстороджный костыль?

2021-03-21 22:50 UTC, Betchika99 commented on src/views/HomeView/HomeView.pug
> -                className: 'film_link_1',
почему 1?)

2021-03-22 07:03 UTC, timoninas commented on src/components/Header/Header.scss
> +    .item__dropdown-profile:hover {
Не знал, что так вообще можно сделать 🧐

2021-03-22 07:04 UTC, timoninas commented on src/index.html
> +    <div id="app"></div>
👀

2021-03-28 11:42 UTC, timoninas commented on src/views/DetailView/DetailView.js
> +            const profileView = new ProfileView();
Никита это переделал в своей ветке

2021-03-28 20:25 UTC, Betchika99 requested changes
- [x] починить проверку авторизации
- [ ] починить отправку запросов (корсы)

2021-03-28 20:25 UTC, Betchika99 commented on server/index.js
> +app.use('/favicon.ico', express.static('src/assets/favicon.ico'));
респект! только по-хорошему ее надо добавлять не в сервер, а в index.html сразу

2021-03-28 20:25 UTC, Betchika99 commented on src/components/FilmCard/FilmdCard.scss
> +        border: 2px solid #fff;
почему цвет не константа?

2021-03-28 20:25 UTC, Betchika99 commented on src/components/Header/Header.scss
> +      .dropdown-profile__image {
почему бы не использовать `&__image` ? здесь и далее. Это ж scss!

2021-03-28 20:25 UTC, Betchika99 commented on src/components/Header/Header.scss
> +            background-color: $dropdown-background-hovered#0e1212;
хм, что за цвет такой?

2021-03-31 19:24 UTC, Betchika99 approved these changes
- [ ] Дропдаун появляется при наведении на лупу. Нужно отредактировать область ховера

2021-03-31 19:24 UTC, Betchika99 commented on server/index.js
> +});
ссылка на видео должна быть с бека, моки не катят

2021-03-31 19:24 UTC, Betchika99 commented on src/components/Header/Header.pug
> +    var headerLinks = [
const

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        this.isMoreThanOneHour =  this.video.duration > 600;
давай магические константы 100 и 600 вынесем в переменные, которые понятно назовем

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +            throw new Error('VideoPlayer or Video is not defined');
и куда эта ошибка полетит? как ее обработаем?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        this.videoPlayer.style.visibility = this.isVisible ? 'hidden': 'visible';
если this.videoPlayer === undefined, тут будет эксепшен

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        this.video[this.isVisible ? 'play': 'pause']();
хм, не особо понятно. По сигнатуре this.video - это селектор. Как можно вызвать селектор?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        this.videoPlayer.querySelector('.js-fullscreen').addEventListener('click', this.toggleFullScreen.bind(this));
1) в современном js мало кто использует bind. Лучше функции делать стрелочными, тогда контекст (и this) привяжется сразу верно
2) нужно добавить обработку на не найденный селектор (например `this.videoPlayer.querySelector('...')?.addEventListener(...))`, иначе будет ошибка
3) где отписка от обработчиков?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +                if (this.video.volume + 0.1 >= 1 ) {
магические непонятные константы выносим в переменные

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +            }
кажется, в этой функции был бы уместен switch case, чем такой вложенный иф

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +    }
а почему именно 15?)

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +    checkFullScreen() {
это функция не просто проверяет, судя по коду. Нужно переименовать ближе к смыслу

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        return number < 10 ? `0${number}` : `${number}`;
почему 10?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +    fixNumber(number) {
что за Number и зачем его fix?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +    }
эта функция выглядит как хелпер для форматирования => можно вынести в утилитку

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.js
> +        hint.style.left = `${event.clientX - (left + (hint.offsetWidth / 2))}px`;
если hint не был найден, тут будут кругом ошибки(

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.scss
> +    #{$self}__fullscreen & {
почему self, а не просто & ?

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.scss
> +    padding: 3px 6px;
padding-и должны быть кратны 5, margin-ы - кратны 4

2021-03-31 19:24 UTC, Betchika99 commented on src/components/VideoPlayer/VideoPlayer.scss
> +    transition: all 0.15s ease-in-out;
основной стиль лучше поднять выше сразу под `&__volume {`

2021-03-31 19:24 UTC, Betchika99 commented on server/index.js
> +/*eslint-disable */
это что?

2021-03-31 19:53 UTC, merged