RT-78: Переделать архитектуру проекта на MV*
frontend-park-mail-ru/2021_1_RedTech pull request #25
Opened 2021-04-02 21:10 UTC by VolkovNik

2021-04-05 21:57 UTC, Betchika99 requested changes
- [x] Проверь пустые строчки в конце файлов
- [x] Добавить js-doc с описанием классов/функций
- [ ] Убрать bind
- [ ] Не использовать в одном файле разные методы с одинаковыми названиями (изменить названия)
- [ ] Добавить .catch к промисам
- [ ] Отписки от событий EventBus
- [ ] Убрать лишние ветки else
- [ ] Вынести новые урлы в соответствующие константы
- [ ] Добавить проверки того, что вернули селекторы (querySelector и тп), а то может быть undefined

2021-04-05 21:57 UTC, Betchika99 commented on .eslintrc.js
> +        'puglatizer': true
зачем пробельчик?

2021-04-05 21:57 UTC, Betchika99 commented on .gitignore
> +index.csss
это что за файл такой? откуда берется?

2021-04-05 21:57 UTC, Betchika99 commented on package.json
> +  ],
по-хорошему настройки лихтера лучше выносить в конфиг линтера. По идее там есть такая секция для игнора

2021-04-05 21:57 UTC, Betchika99 commented on src/components/ProfileContent/ProfileContent.pug
> +            +form(inputs, buttonName, inputWrapper, img)
пустая строка =(

2021-04-05 21:57 UTC, Betchika99 commented on src/main.js
> +import eventBus from './modules/eventBus.js';
давай везде одинаково eventBus называть

2021-04-05 21:57 UTC, Betchika99 commented on src/main.js
> +/*eslint no-unused-vars: */
зачем? и зачем тогда ниже созданы инстансы контроллеров?

2021-04-05 21:57 UTC, Betchika99 commented on src/main.js
> +eventBus.emit('homepage:render');
если этот файл - точка входа в приложение, означает ли это, что этот эмит не сработает? потому что подписки еще не было. или нет?

2021-04-05 21:57 UTC, Betchika99 commented on src/models/detailPage.js
> +        this.eventBus.on('detailpage:getDetailsAboutFilm', this.getDetailsAboutFilm.bind(this));
в современном JS-е обычно не используют bind без надобности. Вместо них лучше использовать _стрелочные функции_ (в классах можно делать стрелочные методы), они привязываются к тому контексту (тому this), где объявлены

2021-04-05 21:57 UTC, Betchika99 commented on src/models/detailPage.js
> +        getDetailFilmPage(filmId).then((film) => {
смущают одинаковые названия, это путает. + нет catch

2021-04-05 21:57 UTC, Betchika99 commented on src/models/detailPage.js
> +        this.eventBus.on('detailpage:getDetailsAboutFilm', this.getDetailsAboutFilm.bind(this));
а отписка где?

2021-04-05 21:57 UTC, Betchika99 commented on src/models/homePage.js
> +import {getCurrentUser, getLogout, getNewFilms, getNewSeries, getTopFilmsAndSeries} from '../modules/http.js';
пробелы между { }

2021-04-05 21:57 UTC, Betchika99 commented on src/models/homePage.js
> +            this.eventBus.emit('homepage:renderContent', values[0], values[1], values[2]);
не очень понятно, что за переменные `values[0], values[1], values[2]` и что за индексы. Лучше вынести в переменные, воспользоваться деструктуризацией и тп

2021-04-05 21:57 UTC, Betchika99 commented on src/models/homePage.js
> +                this.eventBus.emit('homepage:renderHeader', true);
обычно контекстные параметры передают объектом. Так проще переиспользовать функцию как без параметров, так и с параметрами. Это же позволяют задавать дефолтные значения

2021-04-05 21:57 UTC, Betchika99 commented on src/models/homePage.js
> +        });
а как будет отрисовываться страница, если будет ошибка в запросе? нужно предусмотреть дефолтное состояние страницы, которое будет отрисовано:
а) до отправки запроса (чтобы пользак не ждал, особенно с медленным интернетом )
б) если произошла ошибка запроса (чтобы страница не крашилась в никуда)

2021-04-05 21:57 UTC, Betchika99 commented on src/models/profile.js
> +                }
используем современный js))))
```
const params = {
    login: responseBody.username,
    email: responseBody.email,
    user_avatar: responseBody.avatar ?? 'img/user.png',
};
```

2021-04-05 21:57 UTC, Betchika99 commented on src/models/profile.js
> +        const avatar = avatarInput.files[0];
давай деструктуризацию

2021-04-05 21:57 UTC, Betchika99 commented on src/models/profile.js
> +        formPut.append('avatar', avatar);
а если avatar === undefined?

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/adapters.js
> +    return filmCards;
здесь лучше использовать reduce

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/adapters.js
> +    return newFilmsSeries;
здесь тоже лучше reduce

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/eventBus.js
> +export default new EventBus();
лучше не использовать дефолтные экспорты. Объяснение можно прочитать, например, [тут](https://t.me/why_not_export_default)

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/http.js
> +import {filmJsonToFilm, arrayFilmsToFilmCards, arrayContentToNewFilmsSeries} from './adapters.js';
потерялись пробелы { }

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/http.js
> +        }
можно убрать else и просто написать `return null`

2021-04-05 21:57 UTC, Betchika99 commented on src/modules/http.js
> +        url: URLS.api.mediaContent + '/top' + '?limit=5',
почему не сделать специальный урл для этого? лимит лучше вынести в константу

2021-04-05 21:57 UTC, Betchika99 commented on src/views/BaseView/BaseView.js
> +/** Class representing base view. */
наверно стоит добавить, что он абстрактный

2021-04-05 21:57 UTC, Betchika99 commented on src/views/BaseView/BaseView.js
> +    constructor(eventBus, { data = [] } = {}) {
почему массив? jsdoc не соответствует, у тебя тут дата лежит внутри объекта

2021-04-05 21:57 UTC, Betchika99 commented on src/views/DetailView/DetailView.js
> +        content.innerHTML = template;
content может быть undefined

2021-04-05 21:57 UTC, Betchika99 commented on src/views/DetailView/DetailView.js
> +        const [content] = document.getElementsByClassName('content');
лучше использовать querySelector

2021-04-05 21:57 UTC, Betchika99 commented on src/views/HomeView/HomeView.js
> +        };
каждый перед рендером дата будет чиститься? это ожидаемое поведение? рендер же может вызываться несколько раз

2021-04-05 22:15 UTC, VolkovNik commented on .eslintrc.js
> +        'puglatizer': true
его не хватало, eslint подсвечивал

2021-04-09 11:38 UTC, Betchika99 requested changes
- [ ] пустые строки в конце файла
- [ ] использовать **только** чистые функции
- [ ] корректно использовать метод reduce для массивов

2021-04-09 11:38 UTC, Betchika99 commented on .eslintignore
> +src/templates.js
пустая строка в окне файла

2021-04-09 11:38 UTC, Betchika99 commented on src/components/Loader/Loader.scss
> +  }
может циклом?

2021-04-09 11:38 UTC, Betchika99 commented on src/models/profile.js
> +            }
```
if (!responseBody) {
    this.eventBus.emit('homepage:renderErrorPage');
    return;
}

const params = {
    login: responseBody.username,
    email: responseBody.email,
    user_avatar: responseBody.avatar ?? 'img/user.png',
};

this.eventBus.emit('profile:renderProfileInfo', params);
this.eventBus.emit('profile:setEventListeners', idUser);
```

кажется, так будет читаемее

2021-04-09 11:38 UTC, Betchika99 commented on src/modules/adapters.js
> +};
1) функция не чистая
2) неверное использование reduce

2021-04-09 11:38 UTC, Betchika99 commented on src/modules/eventBus.js
> +            ?.delete(callback.name);
лучше перенести на строку выше

2021-04-09 11:38 UTC, Betchika99 commented on src/modules/eventBus.js
> +    }
`this._listeners[event]?.forEach((listener) => listener(...data));` можно просто вот так

2021-04-09 11:38 UTC, Betchika99 commented on src/modules/urls.js
> +        newSeries: `${currentUrl}/api/media/category/newSeries?limit=${NUMBER_OF_BOTTOM_SLIDER_CONTENT}&type=series`,
NUMBER_OF_BOTTOM_SLIDER_CONTENT - что это?)

2021-04-09 11:38 UTC, Betchika99 commented on src/views/HomeView/HomeView.js
> +            window.scrollTo(0, 0);
если используешь не только в одном месте, лучше вынести в утилиту, чтобы каждый раз не писать 0,0

2021-04-10 12:33 UTC, Betchika99 approved these changes

2021-04-10 12:36 UTC, merged