RT-13: Написать web-сервер
frontend-park-mail-ru/2021_1_RedTech pull request #5
Opened 2021-02-23 21:54 UTC by timoninas

2021-02-23 21:54 UTC, timoninas commented
Мы изначально писали все в ветке dev, и не учитывали нейминг коммитов 👀

2021-02-27 22:06 UTC, Betchika99 requested changes
Привет! 

По поводу фикса на страницах и стилях отписывала [в этом ПРе](https://github.com/frontend-park-mail-ru/2021_1_RedTech/pull/2), замечания здесь дублировать не стала.

В текущей реализации главная страница выглядит немного черновиком + кнопка "Меню" несколько бессмысленна - она никуда не ведет. Переход же по кнопке "Регистрация" имеет одну проблему - не меняется урл в строке браузера. Это значит, что если я перезагружу страницу, я снова попаду на страницу меню, хотя я ожидаю, что останусь на регистрации. Роутинг нужно доработать.

В остальном в целом пойдет :)

2021-02-27 22:06 UTC, Betchika99 commented on package.json
> +  "description": "",
Давай добавим описание

2021-02-27 22:06 UTC, Betchika99 commented on package.json
> +    "start": "DEBUG=* node server",
почему в дебаг-режиме?

2021-02-27 22:06 UTC, Betchika99 commented on server/index.js
> +const path = require("path");
в файле разные кавычки. Давай использовать одинаковые

2021-02-27 22:06 UTC, Betchika99 commented on server/index.js
> +// });
давай уберем комментарии

2021-02-27 22:06 UTC, Betchika99 commented on src/css/main.css
> +a{
не хватает пробела перед скобкой

2021-02-27 22:06 UTC, Betchika99 commented on src/css/main.css
> +}
пустую строку пропустили

2021-02-27 22:06 UTC, Betchika99 commented on src/index.html
> +    <link rel="stylesheet" type="text/css" href="/css/signup.css" />
почему в первом случае href начинается со /, а во втором нет? и зачем здесь signup.css?

2021-02-27 22:06 UTC, Betchika99 commented on src/index.html
> +</html>
пустая строка пропущена

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +const config = {
обычно константы, которые объявляются глобально, называют капсом

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +
лишняя пустая строка

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +}
потерялась точка с запятой

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +function signUpPage() {
почему не arrow function?

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +        '</div>';
смело)) но innerHTML не самая лучшая версия для перерисовки страницы. На текущем этапе это неважно, но для подготовки к РК почитай, почему это плохо

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +function menuPage() {
почему не стрелочная?

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +        .map(([menuKey, {text, href}]) => {
наверно не `menuKey`, а `configKey` все таки. Лайк за деструктуризацию! Давай добавим пробелы между текстом и скобками: `{ text, href }`

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +        .forEach(element => application.appendChild(element))
точки с запятой не хватает в конце

2021-02-27 22:06 UTC, Betchika99 commented on src/main.js
> +application.addEventListener('click', e => {
1) давай обрамлять все параметры функций в круглые скобки для лучшей читаемости
2) e - не особо понятное название для переменной. event лучше подойдет

2021-03-10 15:15 UTC, merged